sudo: false
language: ruby
cache: bundler

before_install: gem update bundler
before_script: bundle update
script: bundle exec rspec

rvm:
  - 2.1
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - jruby-head
  - ruby-head
